#!/usr/bin/env node
// style-census.mjs — static census of visual values in a frontend codebase.
// Zero dependencies. Produces evidence (source: TOOL) for design-system audits:
// literal colors, font sizes/weights/line heights, radii, shadows, spacing, z-index,
// breakpoints, Tailwind arbitrary values, custom-property definitions/usages, near-duplicate colors.
//
// Usage:
//   node style-census.mjs <dir> [<dir>...] [--json] [--top 15] [--near 12]
//
// Limitations: regex-based, not a CSS parser. Values computed at runtime, inherited from libraries,
// or generated by CSS-in-JS helpers may be missed; strings that look like colors may be counted.
// Treat results as signals to inspect, not as a verdict.

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, extname, relative } from 'node:path';

const args = process.argv.slice(2);
const flags = new Set(args.filter(a => a.startsWith('--')));
const opt = (name, def) => {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : def;
};
const optValues = new Set([opt('--top'), opt('--near')].filter(Boolean));
const roots = args.filter(a => !a.startsWith('--') && !optValues.has(a));
if (roots.length === 0) {
  console.error('Usage: node style-census.mjs <dir> [<dir>...] [--json] [--top 15] [--near 12]');
  process.exit(1);
}
const TOP = Number(opt('--top', 15));
const NEAR = Number(opt('--near', 12));

const EXT = new Set(['.css', '.scss', '.sass', '.less', '.styl', '.pcss', '.tsx', '.jsx', '.ts', '.js',
  '.mjs', '.vue', '.svelte', '.astro', '.html', '.mdx']);
const SKIP = new Set(['node_modules', '.git', 'dist', 'build', '.next', '.nuxt', '.svelte-kit', 'out',
  'coverage', 'vendor', '.turbo', '.cache', 'storybook-static', '.output', '.vercel']);

function walk(dir, files = []) {
  let entries;
  try { entries = readdirSync(dir); } catch { return files; }
  for (const name of entries) {
    if (SKIP.has(name) || name.startsWith('.claude')) continue;
    const p = join(dir, name);
    let st;
    try { st = statSync(p); } catch { continue; }
    if (st.isDirectory()) walk(p, files);
    else if (EXT.has(extname(name)) && !/\.min\.(js|css)$/.test(name) && st.size < 2_000_000) files.push(p);
  }
  return files;
}

const counters = {};
const where = {};
function add(cat, value, file) {
  const v = String(value).trim().replace(/\s+/g, ' ').replace(/['"`]/g, '');
  if (!v) return;
  counters[cat] ??= new Map();
  counters[cat].set(v, (counters[cat].get(v) || 0) + 1);
  where[cat] ??= new Map();
  if (!where[cat].has(v)) where[cat].set(v, new Set());
  if (where[cat].get(v).size < 3) where[cat].get(v).add(file);
}

const RE = {
  hex: /(?<![\w&])#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{3,4})(?![\w-])/g,
  fnColor: /\b(?:rgba?|hsla?|oklch|oklab|lab|lch|color)\([^)]*\)/g,
  cssProp: /(?:^|[;{\s])(font-size|font-weight|line-height|border-radius|box-shadow|z-index|margin(?:-(?:top|right|bottom|left|inline|block)(?:-(?:start|end))?)?|padding(?:-(?:top|right|bottom|left|inline|block)(?:-(?:start|end))?)?|gap|row-gap|column-gap)\s*:\s*([^;}{]+)/g,
  jsProp: /\b(fontSize|fontWeight|lineHeight|borderRadius|boxShadow|zIndex|margin(?:Top|Right|Bottom|Left|Inline|Block)?|padding(?:Top|Right|Bottom|Left|Inline|Block)?|gap|rowGap|columnGap)\s*:\s*(['"`]?)([^'"`,}\n]+)\2/g,
  media: /@media[^{]*\((?:min|max)-width\s*:\s*([^)]+)\)/g,
  container: /@container[^{]*\((?:min|max)-width\s*:\s*([^)]+)\)|@container[^{]*\(width\s*[<>]=?\s*([^)]+)\)/g,
  varDef: /(--[\w-]+)\s*:/g,
  varUse: /var\(\s*(--[\w-]+)/g,
  twArbitrary: /\b(?:[a-z]+:)*([a-z][a-z-]*)-\[([^\]\s]+)\]/g,
  twScale: /\b(?:[a-z]+:)*(rounded(?:-[trbl]{1,2})?|shadow|text|font|leading|z)-(none|xs|sm|base|md|lg|xl|[2-9]xl|full|inner|thin|light|normal|medium|semibold|bold|extrabold|black|tight|snug|relaxed|loose|\d+)\b/g,
};

const propCat = p => {
  const k = p.toLowerCase();
  if (k.includes('fontsize') || k === 'font-size') return 'font-size';
  if (k.includes('fontweight') || k === 'font-weight') return 'font-weight';
  if (k.includes('lineheight') || k === 'line-height') return 'line-height';
  if (k.includes('radius')) return 'border-radius';
  if (k.includes('shadow')) return 'box-shadow';
  if (k.includes('zindex') || k === 'z-index') return 'z-index';
  return 'spacing';
};

let tokenRefs = 0, literalColors = 0, filesScanned = 0;
const varDefs = new Set(), varUses = new Map();

for (const root of roots) {
  for (const file of walk(root)) {
    filesScanned++;
    const rel = relative(process.cwd(), file);
    let src;
    try { src = readFileSync(file, 'utf8'); } catch { continue; }
    const isStyle = /\.(css|scss|sass|less|styl|pcss)$/.test(file);

    for (const m of src.matchAll(RE.hex)) { add('color', m[0].toLowerCase(), rel); literalColors++; }
    for (const m of src.matchAll(RE.fnColor)) {
      if (/var\(/.test(m[0])) continue;
      add('color', m[0].toLowerCase(), rel); literalColors++;
    }
    for (const m of src.matchAll(RE.cssProp)) {
      const cat = propCat(m[1]);
      const value = m[2].replace(/!important/, '').trim();
      if (/var\(/.test(value)) { tokenRefs++; continue; }
      if (cat === 'spacing') for (const t of value.split(/\s+/)) { if (/^-?[\d.]+(px|rem|em)$/.test(t)) add('spacing', t, rel); }
      else add(cat, value, rel);
    }
    if (!isStyle) {
      for (const m of src.matchAll(RE.jsProp)) {
        const cat = propCat(m[1]);
        const value = m[3].trim();
        if (/var\(|theme|token|\$\{|^[A-Za-z_][\w.]*$/.test(value) && !/^\d/.test(value)) { tokenRefs++; continue; }
        if (cat === 'spacing') for (const t of value.split(/\s+/)) { if (/^-?[\d.]+(px|rem|em)?$/.test(t)) add('spacing', t, rel); }
        else add(cat, value, rel);
      }
      for (const m of src.matchAll(RE.twArbitrary)) add('tailwind-arbitrary', `${m[1]}-[${m[2]}]`, rel);
      for (const m of src.matchAll(RE.twScale)) add(`tailwind-${m[1].replace(/-[trbl]{1,2}$/, '')}`, `${m[1]}-${m[2]}`, rel);
    }
    for (const m of src.matchAll(RE.media)) add('breakpoint (@media)', m[1], rel);
    for (const m of src.matchAll(RE.container)) add('breakpoint (@container)', m[1] || m[2], rel);
    for (const m of src.matchAll(RE.varDef)) varDefs.add(m[1]);
    for (const m of src.matchAll(RE.varUse)) { varUses.set(m[1], (varUses.get(m[1]) || 0) + 1); tokenRefs++; }
  }
}

// Near-duplicate hex colors (simple RGB distance; signal, not perceptual truth)
function hexToRgb(h) {
  let s = h.slice(1);
  if (s.length === 3 || s.length === 4) s = s.slice(0, 3).split('').map(c => c + c).join('');
  s = s.slice(0, 6);
  return [0, 2, 4].map(i => parseInt(s.slice(i, i + 2), 16));
}
const hexes = [...(counters.color?.keys() || [])].filter(c => c.startsWith('#'));
const near = [];
for (let i = 0; i < hexes.length; i++) for (let j = i + 1; j < hexes.length; j++) {
  const a = hexToRgb(hexes[i]), b = hexToRgb(hexes[j]);
  const d = Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
  if (d > 0 && d <= NEAR) near.push([hexes[i], hexes[j], Math.round(d)]);
}
near.sort((x, y) => x[2] - y[2]);

const undefinedVars = [...varUses.keys()].filter(v => !varDefs.has(v));
const unusedVars = [...varDefs].filter(v => !varUses.has(v));

const summary = {
  roots, filesScanned,
  distinct: Object.fromEntries(Object.entries(counters).map(([k, m]) => [k, m.size])),
  top: Object.fromEntries(Object.entries(counters).map(([k, m]) => [k,
    [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, TOP).map(([value, count]) => ({ value, count, files: [...where[k].get(value)] }))])),
  colorLiterals: literalColors,
  tokenReferences: tokenRefs,
  customProperties: { defined: varDefs.size, used: varUses.size, usedButNotDefinedInScan: undefinedVars.slice(0, 30), definedButUnused: unusedVars.slice(0, 30) },
  nearDuplicateColors: near.slice(0, 30),
};

if (flags.has('--json')) {
  console.log(JSON.stringify(summary, null, 2));
} else {
  const out = [];
  out.push(`# Style census`, '', `Scanned ${filesScanned} files in: ${roots.join(', ')}`, '');
  out.push('| Category | Distinct values |', '|---|---:|');
  for (const [k, n] of Object.entries(summary.distinct).sort()) out.push(`| ${k} | ${n} |`);
  out.push('', `Literal color occurrences: ${literalColors} · token/var references: ${tokenRefs}`);
  out.push(`Custom properties: ${varDefs.size} defined, ${varUses.size} used` +
    (undefinedVars.length ? ` · used but not defined in scanned files: ${undefinedVars.length}` : '') +
    (unusedVars.length ? ` · defined but unused: ${unusedVars.length}` : ''));
  for (const [k, list] of Object.entries(summary.top).sort()) {
    out.push('', `## ${k} (top ${Math.min(TOP, list.length)})`, '');
    for (const { value, count, files } of list) out.push(`- \`${value}\` × ${count} — ${files.join(', ')}`);
  }
  if (near.length) {
    out.push('', `## Near-duplicate hex colors (RGB distance ≤ ${NEAR})`, '');
    for (const [a, b, d] of near.slice(0, 30)) out.push(`- \`${a}\` ~ \`${b}\` (Δ${d})`);
  }
  out.push('', '_Regex-based signal. Confirm in code and rendered UI before reporting a finding._');
  console.log(out.join('\n'));
}
